apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: muchtodo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: container-assessment-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MONGO_URI
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-db-name
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret